### ISSUE TITLE
[Tracking] Build Initial CI/CD for Linux and Windows

### ISSUE THREAD

**Issue by TheLunaticScripter** [chef/effortless#135]
- [x] Build expeditor workflow for releasing artifacts
- [x] Build automated linting into PR workflow
- [x] Research and discover BATS features necessary to do Linux testing
- [x] Build Linux workflow, including scaffolding and downstream user package build, and a few valid test cases for Linux
- [x] Test CACerts for Linux
- [x] Research and discover Pester features necessary to do Windows testing
- [x] Build Windows workflow, including scaffolding and downstream user package build, and a few valid test cases for Windows
- [x] Test CACerts for Windows

------------------------
CI/CD Platform Support

- [x] Linux - scaffolding-chef-infra
- [x] Linux - scaffolding-chef-inspec
- [x] Windows - scaffolding-chef-infra
- [x] Windows - scaffolding-chef-inspec

**Comment by echohack** [comment]
See also: #57

**Comment by TheLunaticScripter** [comment]
This is complete
