### ISSUE TITLE
kernel2 support

### ISSUE THREAD

**Issue by echohack** [chef/effortless#147]
This is an Epic to track and plan the work around full support for kernel2.

While we do have kernel2 builds, many of the dependencies and transitive dependencies are not in stable or do not have builds in `core-plans`. We need to consider a few things:

1. Will we support kernel2 for Effortless?
2. If we do, what is the minimum version of all transitive dependencies that we will support?
3. How can we inject ourselves in the conversation and PRs for the respective transitive dependencies? Some of these are governed by other Chef open source projects. Do we contribute to these projects or do we support some forked version under a different origin?

The list of transitive dependencies includes  the following packages. Part of this epic includes verifying that each of these has a kernel2 supported build pipeline.

- [ ] chef/chef-client/14.13.11/20190530181008
- [ ] core/acl/2.2.53/20190115012136
- [ ] core/attr/2.4.48/20190115012129
- [ ] core/binutils/2.31.1/20190115003743
- [ ] core/bundler/1.17.3/20190416230243
- [ ] core/busybox-static/1.29.2/20190115014552
- [ ] core/bzip2/1.0.6/20190115011950
- [ ] core/cacerts/2018.12.05/20190115014206
- [ ] core/coreutils/8.30/20190115012313
- [ ] core/gcc-libs/8.2.0/20190115011926
- [ ] core/glibc/2.27/20190115002733
- [ ] core/gmp/6.1.2/20190115003943
- [ ] core/grep/3.1/20190115012541
- [ ] core/libarchive/3.3.3/20190305214120
- [ ] core/libcap/2.25/20190115012150
- [ ] core/libffi/3.2.1/20190115154244
- [ ] core/libiconv/1.14/20190115155025
- [ ] core/libtool/2.4.6/20190115012815
- [ ] core/libxml2/2.9.8/20190115154829
- [ ] core/libxslt/1.1.33/20190302013818
- [ ] core/libyaml/0.1.6/20190115222132
- [ ] core/linux-headers/4.17.12/20190115002705
- [ ] core/ncurses/6.1/20190115012027
- [ ] core/openssl-fips/2.0.16/20190115014207
- [ ] core/openssl/1.0.2r/20190305210149
- [ ] core/pcre/8.42/20190115012526
- [ ] core/readline/7.0.3/20190115012607
- [ ] core/ruby/2.5.5/20190416223112
- [ ] core/sed/4.5/20190115012152
- [ ] core/xz/5.2.4/20190115013348
- [ ] core/zlib/1.2.11/20190115003728

**Comment by sam1el** [comment]
The current chef-dk and chef-client supported with kernel 2 have the gollowing

### Chef-client 14.7.17
```
core/acl/2.2.52/20180927170749
core/attr/2.4.47/20180927170740
core/binutils/2.30/20180927162345
core/bundler/1.16.2/20181206231319
core/busybox-static/1.28.1/20180927173649
core/bzip2/1.0.6/20180927170545
core/cacerts/2018.06.20/20180927173225
core/coreutils/8.29/20180927170936
core/gcc-libs/7.3.0/20180927170515
core/glibc/2.23/20180927161247
core/gmp/6.1.2/20180927162622
core/grep/3.1/20180927171220
core/libarchive/3.3.2/20181206221702
core/libcap/2.25/20180927170807
core/libffi/3.2.1/20181206220749
core/libiconv/1.14/20181206221015
core/libtool/2.4.6/20180927171537
core/libxml2/2.9.6/20181206220757
core/libxslt/1.1.31/20181206220842
core/libyaml/0.1.6/20181206221041
core/linux-headers/2.6.39/20180927161217
core/ncurses/6.1/20180927170629
core/openssl/1.0.2n/20180927173225
core/pcre/8.41/20180927171203
core/readline/7.0.3/20180927171248
core/ruby/2.5.1/20181206230651
core/sed/4.4/20180927170810
core/xz/5.2.3/20180927172216
core/zlib/1.2.11/20180927162327```

### chef-dk 3.0.38
core/acl/2.2.52/20180927170749
core/attr/2.4.47/20180927170740
core/binutils/2.30/20180927162345
core/bundler/1.16.2/20181206231319
core/busybox-static/1.28.1/20180927173649
core/cacerts/2018.06.20/20180927173225
core/coreutils/8.29/20180927170936
core/gcc-libs/7.3.0/20180927170515
core/glibc/2.23/20180927161247
core/gmp/6.1.2/20180927162622
core/grep/3.1/20180927171220
core/libcap/2.25/20180927170807
core/libffi/3.2.1/20181206220749
core/libiconv/1.14/20181206221015
core/libtool/2.4.6/20180927171537
core/libxml2/2.9.6/20181206220757
core/libxslt/1.1.31/20181206220842
core/libyaml/0.1.6/20181206221041
core/linux-headers/2.6.39/20180927161217
core/ncurses/6.1/20180927170629
core/openssl/1.0.2n/20180927173225
core/pcre/8.41/20180927171203
core/readline/7.0.3/20180927171248
core/ruby/2.5.1/20181206230651
core/sed/4.4/20180927170810
core/xz/5.2.3/20180927172216
core/zlib/1.2.11/20180927162327```

### Chef-dk 3.4.38
```
core/acl/2.2.52/20180927170749
core/attr/2.4.47/20180927170740
core/binutils/2.30/20180927162345
core/bundler/1.16.2/20181206231319
core/busybox-static/1.28.1/20180927173649
core/cacerts/2018.06.20/20180927173225
core/coreutils/8.29/20180927170936
core/gcc-libs/7.3.0/20180927170515
core/glibc/2.23/20180927161247
core/gmp/6.1.2/20180927162622
core/grep/3.1/20180927171220
core/libcap/2.25/20180927170807
core/libffi/3.2.1/20181206220749
core/libiconv/1.14/20181206221015
core/libtool/2.4.6/20180927171537
core/libxml2/2.9.6/20181206220757
core/libxslt/1.1.31/20181206220842
core/libyaml/0.1.6/20181206221041
core/linux-headers/2.6.39/20180927161217
core/ncurses/6.1/20180927170629
core/openssl/1.0.2n/20180927173225
core/pcre/8.41/20180927171203
core/readline/7.0.3/20180927171248
core/ruby/2.5.1/20181206230651
core/sed/4.4/20180927170810
core/xz/5.2.3/20180927172216
core/zlib/1.2.11/20180927162327```

**Comment by TheLunaticScripter** [comment]
During discussion today with @robbkidd, @skpaterson, @OBrienCommaJosh that first step is to work on getting a build of ruby and the step down the tree to other things to get this completed.
